# Generated by Django 5.2.5 on 2025-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingtrip',
            name='receipt_image_url',
        ),
        migrations.AddField(
            model_name='shoppingtrip',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
