# Generated by Django 5.2.5 on 2025-11-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0002_remove_shoppingtrip_receipt_image_url_and_more'),
    ]

    operations = [
        # First: Add all new fields
        migrations.AddField(
            model_name='shoppinglistitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='last_purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Second: Alter existing fields
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
        # Third: Remove old fields
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='aisle_number',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='bay_number',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='grocery_item',
        ),
        # Fourth: Set constraints (after fields exist)
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together={('family', 'store_name')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together={('shopping_list', 'name', 'brand', 'size')},
        ),
        # Fifth: Set ordering (after fields exist)
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['-is_checked', '-last_purchased_date', 'name']},
        ),
    ]
