# Generated by Django 5.2.5 on 2025-11-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0003_alter_shoppinglistitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='available_at_stores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='enriched_from_barcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='first_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='first_enriched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_enrichments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='grocery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='shopright.groceryitem'),
        ),
    ]
