# Generated by Django 5.2.5 on 2025-11-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0004_groceryitem_available_at_stores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='image_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='image_report_count',
            field=models.IntegerField(default=0),
        ),
    ]
