# Generated by Django 5.2.5 on 2025-11-05 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0005_groceryitem_image_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='store_name',
            field=models.CharField(db_index=True, default='Unknown Store', max_length=200),
        ),
        migrations.AddIndex(
            model_name='groceryitem',
            index=models.Index(fields=['store_name', 'name'], name='shopright_g_store_n_b05191_idx'),
        ),
        migrations.AddIndex(
            model_name='groceryitem',
            index=models.Index(fields=['store_name', 'barcode'], name='shopright_g_store_n_20ad38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groceryitem',
            unique_together={('name', 'brand', 'size', 'store_name')},
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='available_at_stores',
        ),
    ]
