# Generated by Django 5.2.5 on 2025-11-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0007_alter_shoppinglist_unique_together_shoppinglist_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aislelocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aislelocation',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aislelocation',
            name='flag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aislelocation',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aislelocation',
            name='location_description',
            field=models.TextField(blank=True, help_text="e.g., 'Behind fruit section', 'Next to aisle 10 on right'"),
        ),
        migrations.AddField(
            model_name='aislelocation',
            name='location_type',
            field=models.CharField(choices=[('aisle', 'Aisle Number'), ('relative', 'Relative'), ('category', 'Category-Based')], default='aisle', max_length=20),
        ),
        migrations.AlterField(
            model_name='aislelocation',
            name='aisle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='aislelocation',
            index=models.Index(fields=['store_name', 'grocery_item'], name='shopright_a_store_n_a851b6_idx'),
        ),
        migrations.AddIndex(
            model_name='aislelocation',
            index=models.Index(fields=['location_type'], name='shopright_a_locatio_8d1aab_idx'),
        ),
    ]
