# Generated by Django 5.2.5 on 2025-11-06 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0008_alter_aislelocation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aislelocation',
            name='contributors',
        ),
        migrations.CreateModel(
            name='LocationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='shopright.aislelocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'user'], name='shopright_l_locatio_193376_idx')],
                'unique_together': {('location', 'user')},
            },
        ),
    ]
