# Generated by Django 5.2.5 on 2025-11-09 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0009_remove_aislelocation_contributors_locationvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_family_store',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_user_store',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='store_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(condition=models.Q(('family__isnull', False)), fields=('family', 'store_name', 'store_location'), name='unique_family_store_location'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(condition=models.Q(('family__isnull', True), ('user__isnull', False)), fields=('user', 'store_name', 'store_location'), name='unique_user_store_location'),
        ),
    ]
