# Generated by Django 5.2.5 on 2025-11-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0010_add_store_location_to_shoppinglist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('FDA', 'FDA (Food & Drug Administration)'), ('FSIS', 'FSIS (USDA Meat/Poultry)'), ('CPSC', 'CPSC (Consumer Product Safety)')], db_index=True, max_length=10)),
                ('recall_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('classification', models.CharField(choices=[('Class I', 'Class I - Serious health hazard'), ('Class II', 'Class II - Moderate health risk'), ('Class III', 'Class III - Minor violation')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Ongoing', 'Ongoing')], db_index=True, default='Active', max_length=20)),
                ('recall_initiation_date', models.DateField()),
                ('recall_posted_date', models.DateField(db_index=True)),
                ('product_name', models.CharField(db_index=True, max_length=500)),
                ('product_description', models.TextField()),
                ('recalling_firm', models.CharField(db_index=True, max_length=200)),
                ('upc_codes', models.JSONField(blank=True, default=list)),
                ('lot_numbers', models.JSONField(blank=True, default=list)),
                ('distribution_pattern', models.CharField(blank=True, max_length=200)),
                ('stores', models.JSONField(blank=True, default=list)),
                ('reason_for_recall', models.TextField()),
                ('health_hazard_evaluation', models.TextField(blank=True)),
                ('remedy', models.TextField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recall_posted_date', '-classification'],
                'indexes': [models.Index(fields=['source', 'status'], name='shopright_p_source_0ca14a_idx'), models.Index(fields=['recall_posted_date', 'classification'], name='shopright_p_recall__2f3545_idx'), models.Index(fields=['product_name', 'recalling_firm'], name='shopright_p_product_381847_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecallMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_product_name', models.CharField(max_length=300)),
                ('purchased_at_store', models.CharField(max_length=200)),
                ('purchased_date', models.DateField()),
                ('confidence_score', models.IntegerField()),
                ('match_reason', models.TextField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user_response', models.CharField(choices=[('unverified', 'Not verified yet'), ('confirmed', 'User confirmed - it is their product'), ('dismissed', 'User dismissed - not their product'), ('unsure', 'User not sure')], default='unverified', max_length=20)),
                ('user_response_at', models.DateTimeField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('grocery_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopright.groceryitem')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='shopright.productrecall')),
                ('shopping_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopright.shoppingtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recall__recall_posted_date', '-confidence_score'],
                'indexes': [models.Index(fields=['user', 'user_response'], name='shopright_r_user_id_559e81_idx'), models.Index(fields=['notification_sent', 'notified_at'], name='shopright_r_notific_c71d00_idx')],
                'unique_together': {('recall', 'user', 'shopping_trip')},
            },
        ),
    ]
