# Generated by Django 5.2.5 on 2025-11-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0010_remove_shoppinglist_unique_family_store_and_more'),
        ('shopright', '0011_productrecall_recallmatch'),
    ]

    operations = [
    ]
