# Generated by Django 5.2.5 on 2025-11-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0012_add_nutrition_fields'),
        ('shopright', '0012_merge_20251112_0232'),
    ]

    operations = [
    ]
