# Generated by Django for ShopRight account deletion feature
# Apple App Store requirement - Guidelines 5.1.1(v)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0012_add_nutrition_fields'),
    ]

    operations = [
        # Change ShoppingTrip.user to SET_NULL (allows family to keep trips)
        migrations.AlterField(
            model_name='shoppingtrip',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shopping_trips',
                to='auth.user'
            ),
        ),
        # Change ShoppingList.user to SET_NULL (allows family to keep lists)
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='personal_shopping_lists',
                to='auth.user'
            ),
        ),
    ]
