# Generated by Django 5.2.5 on 2025-11-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0013_merge_20251113_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='needs_enrichment',
            field=models.BooleanField(default=False),
        ),
    ]
