# Generated by Django 5.2.5 on 2025-12-06 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0013_account_deletion_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zip_codes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='needs_enrichment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('background_check_date', models.DateField(blank=True, null=True)),
                ('background_check_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=5.0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_zones', models.ManyToManyField(blank=True, to='shopright.deliveryzone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-total_deliveries'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage commission (e.g., 10.0 = 10%)', max_digits=5)),
                ('fulfillment_model', models.CharField(choices=[('store_packs_we_deliver', 'Store Packs, We Deliver'), ('store_full_service', 'Store Packs and Delivers'), ('we_shop_and_deliver', 'We Shop and Deliver')], default='store_packs_we_deliver', help_text='Defines who handles shopping and delivery', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_day', models.CharField(help_text="e.g., 'Saturday'", max_length=20)),
                ('delivery_window', models.CharField(help_text="e.g., '9-11am', '11am-1pm'", max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_instructions', models.TextField(blank=True, help_text='Gate code, parking, special instructions')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic - $15/week (1 store, delivery only)'), ('premium', 'Premium - $30/week (2 stores, delivery + fridge stocking)')], default='basic', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(help_text="Customer's shopping list - store/shopper toggle items directly", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_subscriptions', to='shopright.shoppinglist')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='shopright.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('shopper', 'Personal Shopper'), ('store', 'Store Staff'), ('store_owner', 'Store Owner'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shopright.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly Premium'), ('annual', 'Annual Premium'), ('lifetime', 'Lifetime Premium')], default='free', max_length=50)),
                ('apple_receipt_data', models.TextField(blank=True, null=True)),
                ('apple_transaction_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('daily_nutrition_scans_used', models.IntegerField(default=0)),
                ('last_nutrition_scan_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='WeeklyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('packing', 'Store is packing'), ('ready', 'Ready for pickup'), ('out_for_delivery', 'Shopper is delivering'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('packing_started_at', models.DateTimeField(blank=True, null=True)),
                ('packing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total grocery cost charged by store', max_digits=10, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Commission we earn from store', max_digits=10, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='delivery_receipts/%Y/%m/')),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='shopright.shopper')),
                ('shopping_trip', models.ForeignKey(blank=True, help_text="Links to customer's shopping trip history", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopright.shoppingtrip')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_deliveries', to='shopright.deliverysubscription')),
            ],
            options={
                'verbose_name_plural': 'Weekly Deliveries',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
