# Generated by Django 5.2.5 on 2025-11-19 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0014_groceryitem_needs_enrichment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly Premium'), ('annual', 'Annual Premium'), ('lifetime', 'Lifetime Premium')], default='free', max_length=50)),
                ('apple_receipt_data', models.TextField(blank=True, null=True)),
                ('apple_transaction_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('daily_nutrition_scans_used', models.IntegerField(default=0)),
                ('last_nutrition_scan_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
