# Generated by Django 5.2.5 on 2025-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0014_deliveryzone_groceryitem_needs_enrichment_shopper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for billing', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverysubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID', max_length=100),
        ),
    ]
