# Generated by Django 5.2.5 on 2025-12-02 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0015_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingtrip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
