# Generated by Django 5.2.5 on 2025-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0015_deliverysubscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysubscription',
            name='billing_cycle_end',
            field=models.DateTimeField(blank=True, help_text='End of current billing week (7 days after start)', null=True),
        ),
        migrations.AddField(
            model_name='deliverysubscription',
            name='billing_cycle_start',
            field=models.DateTimeField(blank=True, help_text='Start of current billing week (first delivery date)', null=True),
        ),
        migrations.AddField(
            model_name='deliverysubscription',
            name='deliveries_this_cycle',
            field=models.IntegerField(default=0, help_text='Number of deliveries fulfilled in current billing cycle'),
        ),
        migrations.AddField(
            model_name='deliverysubscription',
            name='pending_schedule',
            field=models.JSONField(blank=True, help_text='Queued changes to apply at next billing cycle: {delivery_day, delivery_window, store_id, shopping_list_id}', null=True),
        ),
    ]
