# Generated by Django 5.2.5 on 2025-12-09 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0016_deliverysubscription_billing_cycle_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysubscription',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Optional - linked when store becomes a partner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='shopright.store'),
        ),
    ]
