# Generated by Django 5.2.5 on 2025-12-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0018_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydelivery',
            name='shopping_list',
            field=models.ForeignKey(default=1, help_text='Shopping list to use for this delivery', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_deliveries', to='shopright.shoppinglist'),
            preserve_default=False,
        ),
    ]
