# Generated by Django 5.2.5 on 2025-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0019_weeklydelivery_shopping_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='shopper_collected',
            field=models.BooleanField(default=False),
        ),
    ]
