# Generated by Django 5.2.5 on 2025-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0020_shoppinglistitem_collected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
