# Generated by Django 5.2.5 on 2025-12-15 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0023_alter_weeklydelivery_shopper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='locked_for_shopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingtrip',
            name='created_by_shopper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingtrip',
            name='shopper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopper_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklydelivery',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('assigned', 'Assigned to Shopper'), ('packing', 'Store is packing'), ('ready', 'Ready for pickup'), ('out_for_delivery', 'Shopper is delivering'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
