# Generated by Django 5.2.5 on 2025-12-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0024_shoppinglist_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydelivery',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost before shopping', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weeklydelivery',
            name='payment_authorization_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for pre-authorization hold', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weeklydelivery',
            name='payment_captured_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount captured from receipt', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weeklydelivery',
            name='payment_charge_id',
            field=models.CharField(blank=True, help_text='Stripe Charge ID after payment capture', max_length=255, null=True),
        ),
    ]
