# Generated by Django 5.2.5 on 2025-12-16 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0025_weeklydelivery_estimated_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingtrip',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='shopright.weeklydelivery'),
        ),
        migrations.AlterField(
            model_name='shoppingtrip',
            name='shopper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopped_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
