# Generated by Django 5.2.5 on 2025-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0027_add_unique_active_delivery_subscription_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydelivery',
            name='delivery_window',
            field=models.CharField(blank=True, help_text="e.g., '9-11 AM' - if null, uses subscription's delivery_window", max_length=20, null=True),
        ),
    ]
