# Generated by Django 5.2.5 on 2026-01-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0028_weeklydelivery_delivery_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_trial_used_at',
            field=models.DateTimeField(blank=True, help_text='When user activated their free trial', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_used_free_trial',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this user already used their 15-day free trial?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text="User's phone number (for trial fraud prevention)", max_length=20),
        ),
    ]
