# Generated by Django 5.2.5 on 2026-01-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopright', '0016_alter_shoppinglist_user_alter_shoppingtrip_user'),
        ('shopright', '0029_userprofile_free_trial_used_at_and_more'),
    ]

    operations = [
    ]
