# Generated by Django 5.2.5 on 2026-04-16 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='plaid_access_token',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance_available',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('institution_name', models.CharField(blank=True, default='', max_length=100)),
                ('institution_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to='shillak.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shillak_plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='plaid_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='shillak.plaiditem'),
        ),
    ]
