# Generated by Django 5.2.5 on 2026-04-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0002_remove_bankaccount_plaid_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='last_alert_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
