# Generated by Django 5.2.5 on 2026-04-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0003_bankaccount_last_alert_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('method', models.CharField(choices=[('zelle', 'Zelle'), ('venmo', 'Venmo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='shillak.bankaccount')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shillak_transfer_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='shillak.home')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shillak_transfer_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
