# Generated by Django 5.2.5 on 2026-04-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0004_transferrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('predicted_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('predicted_min_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_end_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('bills_due', models.JSONField(default=list)),
                ('recurring_bills', models.JSONField(default=list)),
                ('income_patterns', models.JSONField(default=list)),
                ('alerts', models.JSONField(default=list)),
                ('monthly_summary', models.JSONField(default=dict)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_predictions', to='shillak.home')),
            ],
            options={
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('personal_finance_category', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shillak.bankaccount')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shillak.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shillak_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
