# Generated by Django 5.2.5 on 2026-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0005_cashflowprediction_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowprediction',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
    ]
