# Generated by Django 5.2.5 on 2026-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0006_cashflowprediction_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowprediction',
            name='alerted_at_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
