# Generated by Django 5.2.5 on 2026-04-23 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillak', '0007_cashflowprediction_alerted_at_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_aliases', to='shillak.home')),
            ],
            options={
                'unique_together': {('home', 'normalized_name')},
            },
        ),
    ]
